### PR TITLE
Fixing installation for node v4.2.1

### LINKED ISSUE #48: compile error
```
> node-core-audio@0.5.0 install /Users/tony/src/icecast_client/node_modules/node-core-audio
> node-gyp rebuild

  CXX(target) Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o
In file included from ../NodeCoreAudio/AudioEngine.cpp:9:
In file included from /Users/tony/src/icecast_client/node_modules/node-core-audio/NodeCoreAudio/AudioEngine.h:11:
/Users/tony/.node-gyp/4.2.1/include/node/node_internals.h:6:10: fatal error: 'util-inl.h' file not found
#include "util-inl.h"
         ^
1 error generated.
make: *** [Release/obj.target/NodeCoreAudio/NodeCoreAudio/AudioEngine.o] Error 1
```

I'm using node 4
```
$ node --version
v4.2.1
```

### PR DESCRIPTION
**Pull request by vsukhomlinov**
Upgrading Nan to latest so that package can be installed on node 4.2.1(LTS)
Fixes #48, #49 

Any suggestions on how to write a test that covers most of logic?

### CODE REVIEW

**Comment by vsukhomlinov** [comment]
Hey @ZECTBynmo, just wandering, are you still maintaining this project?

**Comment by ZECTBynmo** [comment]
@vsukhomlinov Thanks for the pull request. I'm theoretically still maintaining the project, but I have a _lot_ of real world stuff going on right now, including some health issues, so I'm doubly appreciative for the help.

I'll hopefully get a chance to look over this PR this week some time and push out an npm update, but I can't promise anything. If someone else (maybe one of the creators of the issues you mentioned) comes in here and vouches for the patch, I'll accept it on faith :)

**Comment by mzgoddard** [comment]
I'm not one of the issue creators but I can state that it builds on my main machine and works on Node 4.2.1 on Mac OS X El Capitan.

**Comment by ZECTBynmo** [comment]
Thanks @vsukhomlinov and @mzgoddard. Sorry for my slow progress
